// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZSj_H_Bop1NB0NkOrmltchrx-2bN19SQ',
    appId: '1:200329681504:android:8c2c06e493ada1933d8105',
    messagingSenderId: '200329681504',
    projectId: 'lotteryapp-a5eab',
    storageBucket: 'lotteryapp-a5eab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6ZzJqnOB0py5lJ04lrlvFjPbh5xAMw1c',
    appId: '1:200329681504:ios:4554c6871e2ec03a3d8105',
    messagingSenderId: '200329681504',
    projectId: 'lotteryapp-a5eab',
    storageBucket: 'lotteryapp-a5eab.firebasestorage.app',
    iosBundleId: 'com.zcodes.org',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLDStavyTDcx6bElUee13ndYC8O0VBAPg',
    appId: '1:200329681504:web:805cab05e59fa4c63d8105',
    messagingSenderId: '200329681504',
    projectId: 'lotteryapp-a5eab',
    authDomain: 'lotteryapp-a5eab.firebaseapp.com',
    storageBucket: 'lotteryapp-a5eab.firebasestorage.app',
  );

}